export function createAdministration({el,button,api,send,refresh,isBusy,getInfo,message,handleError}){
 let invite=null;
 function acceptResult(result){if(result.초대토큰)invite={...result};}
 const appendField=(f,l)=>f.insertBefore(l,f.querySelector(':scope > .admin-footer'));
 const textField=(f,label,value='',type='text')=>{const l=el('label',label),i=el(type==='textarea'?'textarea':'input');if(type!=='textarea')i.type=type;else i.rows=2;i.value=value;i.required=true;i.setAttribute('aria-label',label);l.append(i);appendField(f,l);return i;};
 const select=(f,label,items,value,empty=null)=>{const l=el('label',label),i=el('select');i.setAttribute('aria-label',label);if(empty!==null)i.append(new Option(empty,''));for(const x of items)i.append(new Option(x.name,x.id));i.value=value||'';l.append(i);appendField(f,l);return i;};
 function checked(f,label,value){const l=el('label',label,'check-label'),i=el('input');i.type='checkbox';i.checked=value;i.setAttribute('aria-label',label);l.prepend(i);appendField(f,l);return i;}
 function fold(label){const d=el('details');d.append(el('summary',label));return d;}
 function form(data,kind,args,label){const f=el('form',null,'admin-form');const reason=textField(f,'변경 사유','','textarea');reason.maxLength=2000;const err=el('p','','error');err.setAttribute('role','alert');const b=el('button',label,'primary');b.type='submit';const footer=el('div',null,'admin-footer');footer.append(reason.parentElement,err,b);f.append(footer);
  f.addEventListener('submit',async e=>{e.preventDefault();if(isBusy())return;try{err.textContent='';const result=await send({종류:kind,기대설정개정:data.설정개정,인자:{...args(),사유:reason.value}},'admin');if(result){acceptResult(result);await refresh();message('설정을 저장했습니다. 변경 이력을 확인할 수 있습니다.');}}catch(e){err.textContent=e.message;if(e.status===401)handleError(e);if(e.status===409)message('최신 설정을 새로고침해 확인하세요. 작성한 내용은 유지됩니다.',true);}});return f;
 }
 function memberForm(data,m){const box=el('div');let name,email,department,active;const f=form(data,'구성원저장',()=>({구성원ID:m?.id||null,표시명:name.value,이메일:email.value,부서ID:department.value,활성:active?.checked||false}),m?'구성원 저장':'초대 대기 계정 등록');
  name=textField(f,'구성원 이름',m?.표시명||'');name.maxLength=100;email=textField(f,'구성원 이메일',m?.이메일||'','email');email.maxLength=254;department=select(f,'구성원 부서',data.부서.filter(d=>d.활성).map(d=>({id:d.id,name:d.이름})),m?.부서_id||data.부서.find(d=>d.활성)?.id);department.required=true;
  if(m?.접속준비)active=checked(f,'계정 활성',m.활성);else f.append(el('p','최초 접속 초대를 수락하면 계정이 활성화됩니다.','hint'));
  box.append(f);if(m){if(!m.접속준비){const d=fold('최초 접속 초대');d.append(form(data,'계정초대발급',()=>({구성원ID:m.id}),'최초 접속 초대 발급'));box.append(d);}
    else{const d=fold('기존 세션 만료');d.append(el('p','이 계정으로 로그인한 모든 세션을 만료합니다. 이후 다시 로그인할 수 있습니다.','hint'),form(data,'세션만료',()=>({구성원ID:m.id}),'모든 세션 만료'));box.append(d);}}
  return box;
 }
 async function render(){const data=await api('read',{종류:'운영설정'}),box=el('div',null,'admin-settings');
  const ready=el('section',null,'detail-card');ready.append(el('h2','구성 설정 점검'),el('p',`설정 개정 ${data.설정개정} · 부서 ${data.부서.length}개 · 활성 계정 ${data.구성원.filter(m=>m.활성).length}명`,'hint'));
  if(data.점검.length){const list=el('ul');for(const i of data.점검)list.append(el('li',i.내용));ready.append(list);}else ready.append(el('p','계정과 승인 경로의 기본 설정을 확인했습니다.','success'));
  ready.append(el('p','실제 명단 확인, 실무 시나리오와 복구 검증을 마친 뒤 시범 운영을 시작하세요.','hint'));box.append(ready);
  if(invite){const section=el('section',null,'detail-card invite-output');section.append(el('h3','최초 접속 초대 링크'),el('p',`만료: ${new Date(invite.만료시각).toLocaleString('ko-KR')} · 한 번 사용`));const link=new URL(location.pathname,location.origin);link.hash='invite='+invite.초대토큰;const label=el('label','초대 링크'),input=el('input');input.readOnly=true;input.value=link.href;input.setAttribute('aria-label','초대 링크');label.append(input);section.append(label,el('p','이 링크를 해당 구성원에게 직접 전달하세요. 새로 발급하면 이전 링크는 사용할 수 없습니다.','hint'),button('링크 선택','secondary',()=>{input.focus();input.select();}),button('링크 표시 닫기','text-button',()=>{invite=null;section.remove();}));box.append(section);}
  const people=el('section',null,'detail-card');people.append(el('h2','구성원'));const add=fold('새 구성원 등록');add.append(memberForm(data,null));people.append(add);
  for(const m of data.구성원){const dept=data.부서.find(d=>d.id===m.부서_id),d=fold(`${m.표시명} · ${dept?.이름||''} · ${m.활성?'사용':m.접속준비?'중지':'초대 대기'}`);d.classList.add('admin-member');d.dataset.memberId=m.id;d.append(el('p',m.이메일),el('p',`진행 업무 참여 ${m.진행참여수}건 · ${data.역할.filter(r=>r.구성원_id===m.id).map(r=>r.역할).join(', ')||'일반 구성원'}`,'hint'),memberForm(data,m));people.append(d);}box.append(people);
  const routes=el('section',null,'detail-card');routes.append(el('h2','승인 경로'),el('p','새 요청부터 지정한 담당자에게 전달합니다. 이미 배정된 승인과 기존 승인자의 역할은 유지됩니다.','hint'));
  for(const dept of [null,...data.부서.filter(d=>d.활성)]){const current=dept?dept.승인자ID:data.대표승인자ID,d=fold(dept?`${dept.이름} 접수 승인자`:'대표 승인자');let person;const f=form(data,'승인경로설정',()=>({부서ID:dept?.id||null,구성원ID:person.value||null}),'승인 경로 저장');person=select(f,'승인 담당자',data.구성원.filter(m=>m.활성&&(!dept||m.부서_id===dept.id)).map(m=>({id:m.id,name:m.표시명})),current,'미지정');d.append(f);routes.append(d);}box.append(routes);
  const roles=el('section',null,'detail-card');roles.append(el('h2','권한 관리'),el('p','관리자는 조직 설정을 관리합니다. 업무 내용 열람이나 대표·부서 승인을 자동으로 허용하지 않습니다.','hint'));
  let person,role,department,grant;const rf=form(data,'역할설정',()=>({구성원ID:person.value,역할:role.value,부서ID:role.value==='부서승인자'?department.value:null,부여:grant.checked}),'역할 설정 저장');person=select(rf,'권한 대상',data.구성원.map(m=>({id:m.id,name:m.표시명+(m.활성?'':' (중지·초대 대기)')})),getInfo().본인.ID);role=select(rf,'역할',['관리자','부서승인자','대표승인자'].map(x=>({id:x,name:x})),'관리자');department=select(rf,'권한 부서',data.부서.map(d=>({id:d.id,name:d.이름})),data.부서[0].id);department.parentElement.hidden=true;role.addEventListener('change',()=>{department.parentElement.hidden=role.value!=='부서승인자';});grant=checked(rf,'역할 부여 (해제하려면 체크 해제)',true);roles.append(rf);box.append(roles);
  const departments=el('section',null,'detail-card');departments.append(el('h2','부서와 처리 기한'));
  for(const dept of [null,...data.부서]){const d=fold(dept?`${dept.이름} 부서 설정`:'새 부서 등록');let code,name,zone,active;const f=form(data,'부서저장',()=>({부서ID:dept?.id||null,코드:code.value,이름:name.value,시간대:zone.value,활성:active.checked}),'부서 설정 저장');code=textField(f,'부서 코드',dept?.코드||'');code.readOnly=Boolean(dept);code.maxLength=40;name=textField(f,'부서 이름',dept?.이름||'');name.maxLength=100;zone=textField(f,'부서 시간대',dept?.시간대||'Asia/Seoul');zone.maxLength=100;active=checked(f,'부서 활성',dept?.활성??true);d.append(f);departments.append(d);}
  const deadline=fold('처리 기한 기본값');let key,days;const df=form(data,'기한설정',()=>({키:key.value,영업일:Number(days.value)}),'처리 기한 저장');key=select(df,'다음 행동',data.기한.map(k=>({id:k.키,name:k.키})),data.기한[0].키);days=textField(df,'처리 영업일',String(data.기한[0].영업일),'number');days.min='1';days.max='365';key.addEventListener('change',()=>{days.value=data.기한.find(k=>k.키===key.value).영업일;});deadline.append(el('p','새로 생성되는 차례부터 적용합니다. 기존 차례의 기한은 유지됩니다.','hint'),df);departments.append(deadline);box.append(departments);
  const history=el('section',null,'detail-card');history.append(el('h2','설정 변경 이력'),el('p','최근 50건 · 초대 비밀과 비밀번호는 기록하지 않습니다.','hint'));for(const row of data.이력){const d=fold(`${row.종류} · ${row.작성자||'운영자'} · ${new Date(row.시각).toLocaleString('ko-KR')}`);d.append(el('p',row.내용.사유||'계정 접속 설정'),el('pre',JSON.stringify(row.내용,null,2)));history.append(d);}box.append(history);return box;
 }
 return {render,acceptResult,reset(){invite=null;}};
}
